# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Experiments in simplicity
email:
description: > # this means to ignore newlines until "baseurl:"
  Remove the trivial many. Focus on the vital few.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://awolski.com" # the base hostname & protocol for your site
github_username:  awolski
permalink: /:slug/

# Build settings
markdown: kramdown
